version: '2'
services:
  rediskey-app:
    image: rediskey
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://rediskey-postgresql:5432/rediskey
      - JHIPSTER_CACHE_REDIS_SERVER=redis://rediskey-redis:6379
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  rediskey-postgresql:
    extends:
      file: postgresql.yml
      service: rediskey-postgresql
  rediskey-redis:
    extends:
      file: redis.yml
      service: rediskey-redis
